version: "3.9"
services:
  web:
    build: ./SearchStory.App/
    command: "/bin/bash ./entrypoint.sh"
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./SearchStory.App/:/app
    environment: 
      - DOTNET_URLS="http://*:5000;https://*:5001"
      - PASSWORD=$PASSWORD